<footer>
    <div>
        <span class="footer-link-header">Services</span>
        <div class="footer-link-container">
            <a class="footer-link-item">Studio</a>
            <a class="footer-link-item">Video Maker</a>
            <a class="footer-link-item">Meme Generator</a>
            <a class="footer-link-item">Add Subtitles</a>
            <a class="footer-link-item">Add Audio</a>
            <a class="footer-link-item">Video Resizer</a>
            <a class="footer-link-item">Loop Video</a>
            <a class="footer-link-item">Video Trimmer</a>
        </div>
    </div>
    <div>
        <span class="footer-link-header">Information</span>
        <div class="footer-link-container">
            <a class="footer-link-item">Story Templates</a>
            <a class="footer-link-item">Border Templates</a>
            <a class="footer-link-item">Meme Templates</a>
            <a class="footer-link-item">Collage Maker</a>
            <a class="footer-link-item">Animated Text</a>
        </div>
    </div>
    <div>
        <span class="footer-link-header">Viemeo</span>
        <div class="footer-link-container">
            <div class="row" style="padding-left: 15px;">
                <a class="footer-link-item">
                    <svg viewBox="0 0 64 64" width="32" height="32">
                        <circle cx="32" cy="32" r="31" fill="#3b5998"></circle>
                        <path d="M34.1,47V33.3h4.6l0.7-5.3h-5.3v-3.4c0-1.5,0.4-2.6,2.6-2.6l2.8,0v-4.8c-0.5-0.1-2.2-0.2-4.1-0.2 c-4.1,0-6.9,2.5-6.9,7V28H24v5.3h4.6V47H34.1z" fill="white"></path>
                    </svg>
                </a>
                <a href="" class="footer-icon">
                    <img src="https://i.imgur.com/MTYvR0K.png" alt="Instagram Icon" class="footer-instagram-image">
                </a>
                <a class="footer-icon">
                    <img src="../media/icon/icon-github.svg" alt="Github Icon">
                </a>
            </div>                  
        </div>
    </div>
</footer>