<?php
session_start();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Viemeo</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/jpg" href="../../images/logo/vie-logo.jpg" />
    <link rel="stylesheet" type="text/css" href="../font/css/style.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="../font/js/font.js"></script>
</head>
<body>
    <div class="height-header">
        <div class="align-header-left">
            <div class="align-header-center">
                <span><a class="logo-text" href="../view/index.php">Viemeo</a></span>
            </div>
        </div>
        <div class="align-header-right">
            <ul class="category">
                <li class="category-item"><a href="">Tools</a>
                    <div class="sub-category-hover">
                        <ul class="sub-category">
                            <li class="sub-category-item">
                                <div>
                                    <img class="category-img" src="../media/banner/category-1.png" alt="Studio">
                                    <a href="">Studio</a>
                                </div>
                            </li>
                            <li class="sub-category-item">
                                <div>
                                    <img class="category-img" src="../media/banner/category-2.png" alt="Studio">
                                    <a href="">Video Macker</a>
                                </div> 
                            </li>
                            <li class="sub-category-item">
                                <div>
                                    <img class="category-img" src="../media/banner/category-3.png" alt="Studio">
                                    <a href="">Meme Generator</a>
                                </div>
                            </li>
                            <li class="sub-category-item">
                                <div>
                                    <img class="category-img" src="../media/banner/category-5.png" alt="Studio">
                                    <a href="">Subtitler</a>
                                </div>
                            </li>
                            <li class="sub-category-item">
                                <div>
                                    <img class="category-img" src="../media/banner/category-4.png" alt="Studio">
                                    <a href="">Trim Video</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="category-item"><a href="">Collections</a></li>
                <li class="category-item"><a href="">Pricing</a></li>
                <li class="category-item"><a href="">Resouces</a></li>
                <li class="category-item">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor" color="#3e1e20">
                        <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
                        <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                        <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
                    </svg>
                    <a href="../../viemeo/view/signin.php">
                        <?php
                            //session_start();
                            if (isset($_SESSION['username']) == null) {
                                echo 'Sign In';
                            }
                            else{
                                echo $_SESSION['username'];
                            }
                        ?>
                    </a>
                    <span class="signin-menu">
                        <button onclick="signinMenu()" style="background-color: transparent;"  id="caret-down-fill">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-caret-down-fill" fill="currentColor" color="#3e1e20">
                                <path d="M7.247 11.14L2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                            </svg>
                            <svg class="caret-up-fill" width="1em" height="1em" viewBox="0 0 16 16" display="none" class="bi bi-caret-up-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M7.247 4.86l-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0 0 0 .753-1.659l-4.796-5.48a1 1 0 0 0-1.506 0z"/>
                            </svg>
                        </button>
                        <!-- <button style="background-color: transparent;">
                            <svg class="caret-up-fill" width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-caret-up-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M7.247 4.86l-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0 0 0 .753-1.659l-4.796-5.48a1 1 0 0 0-1.506 0z"/>
                            </svg>
                        </button> -->
                        <ul class="sub-signin-menu">
                            <li><a href="">Your Profile</a></li>
                            <li><a href="">Yous Projects</a></li>
                            <li><a href="">Settings</a></li>
                            <li><a href="">Help</a></li>
                            <li><a href="">Sign Out</a></li>
                        </ul>
                    </span>
                </li>
            </ul>
        </div>
    </div>
</body>
</html>